import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import Providers from '../components/Providers'
import { Toaster } from 'sonner'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pulse eCommerce: Shop latest Tech',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} relative h-full antialiased tracking-wide`}>
        <main className='ralative flex flex-col'>
          <Providers>
            <Navbar />
            <div className="flex-grow flex-1">
              {children}
            </div>
          </Providers>
        </main>
        <Toaster position='top-center' richColors/>
      </body>
    </html>
  )
}
